services:
  rorn-tool:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tool
    volumes:
      - tools:/var/lib/postgresql/data
    restart: always

volumes:
  tools:
